/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 aegircolor.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/aegircolor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.head3d.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/aegircolor-transformed.glb')
