/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 aegir6013myndbandpaelinggata.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/aegir6013myndbandpaelinggata-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.roupellstreet2108B} position={[0.34, -1.9, -22.69]} rotation={[-0.03, 0, 0]} scale={[1.51, 1.51, 25.25]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.roupellstreet2108B} position={[-4.27, 0.72, -1.97]} rotation={[-0.04, 0, 0]} scale={[1, 2.3, 95.7]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.roupellstreet2108B} position={[4.48, 0.72, -1.97]} rotation={[-0.04, 0, 0]} scale={[-1, 2.3, 95.7]} />
      <mesh geometry={nodes['Screenshot_2020-12-15_at_103800'].geometry} material={materials['Screenshot 2020-12-15 at 10.38.00']} position={[0, 1.66, -27.79]} rotation={[Math.PI / 2, 0, 0]} scale={6.69} />
    </group>
  )
}

useGLTF.preload('/aegir6013myndbandpaelinggata-transformed.glb')
