/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 harmaborg8.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/harmaborg8-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/harmaborg8-transformed.glb')
